# Generated by Django 3.0.5 on 2020-04-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('isin', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
            },
        ),
    ]
