# Generated by Django 6.0.6 on 2026-07-03 16:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import stockings.settings
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63)),
            ],
            options={
                'verbose_name': 'Depot',
                'verbose_name_plural': 'Depots',
            },
        ),
        migrations.CreateModel(
            name='DepotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotitems', to='stockings.depot')),
            ],
            options={
                'verbose_name': 'DepotItem',
                'verbose_name_plural': 'DepotItems',
            },
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('FEE', 'Fee')], max_length=10)),
                ('currency', models.CharField(default=stockings.settings._read_default_currency, max_length=3)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('_price_per_unit', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('_fees', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('_taxes', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='stockings.depotitem')),
            ],
            options={
                'verbose_name': 'Cashflow',
                'verbose_name_plural': 'Cashflows',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='stockings.portfolio'),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default=stockings.settings._read_default_currency, max_length=3)),
            ],
            options={
                'verbose_name': 'StockItem',
                'verbose_name_plural': 'StockItems',
                'constraints': [models.UniqueConstraint(fields=('isin', 'currency'), name='unique_isin_per_currency')],
            },
        ),
        migrations.AddField(
            model_name='depotitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockings.stockitem'),
        ),
        migrations.AlterUniqueTogether(
            name='depot',
            unique_together={('portfolio', 'name')},
        ),
        migrations.CreateModel(
            name='StockItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_value', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stockings.stockitem')),
            ],
            options={
                'verbose_name': 'StockItemPrice',
                'verbose_name_plural': 'StockItemPrices',
                'ordering': ['-_timestamp', 'stock_item'],
                'get_latest_by': '_timestamp',
                'constraints': [models.UniqueConstraint(models.F('stock_item'), django.db.models.functions.datetime.TruncDate('_timestamp'), name='unique_stock_item_price_per_day')],
            },
        ),
    ]
