# Generated by Django 3.0.5 on 2020-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('isin', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('_latest_price_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('_latest_price_currency', models.CharField(blank=True, max_length=3)),
                ('_latest_price_timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
            },
        ),
    ]
