# Generated by Django 6.0.6 on 2026-06-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0002_depot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('isin', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'StockItem',
                'verbose_name_plural': 'StockItems',
            },
        ),
    ]
