# Generated by Django 3.0.5 on 2020-04-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0002_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='_latest_price_value',
            new_name='_latest_price_amount',
        ),
    ]
