# Generated by Django 3.0.5 on 2020-04-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0003_rename_value_to_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_deposit_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('_deposit_currency', models.CharField(blank=True, max_length=3)),
                ('_deposit_timestamp', models.DateTimeField(null=True)),
                ('_stock_count', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockings.Portfolio')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stockings.StockItem')),
            ],
            options={
                'verbose_name': 'Portoflio Item',
                'verbose_name_plural': 'Portfolio Items',
                'unique_together': {('portfolio', 'stock_item')},
            },
        ),
    ]
