# Generated by Django 6.0.6 on 2026-06-17 07:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0003_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_value', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('_timestamp', models.DateField(default=datetime.date.today)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stockings.stockitem', unique_for_date='_price_timestamp')),
            ],
            options={
                'verbose_name': 'StockItemPrice',
                'verbose_name_plural': 'StockItemPrices',
                'ordering': ['-_timestamp', 'stock_item'],
                'get_latest_by': '_timestamp',
            },
        ),
    ]
