# Generated by Django 3.0.5 on 2020-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0004_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='_deposit_currency',
            field=models.CharField(blank=True, default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='_latest_price_currency',
            field=models.CharField(blank=True, default='EUR', max_length=3),
        ),
    ]
