# Generated by Django 6.0.6 on 2026-06-17 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0004_stockitemprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depotitems', to='stockings.depot')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockings.stockitem')),
            ],
            options={
                'verbose_name': 'DepotItem',
                'verbose_name_plural': 'DepotItems',
            },
        ),
    ]
