# Generated by Django 3.0.5 on 2020-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0005_auto_20200427_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='_deposit_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='_deposit_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='_latest_price_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='_latest_price_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
