# Generated by Django 6.0.6 on 2026-06-17 11:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0005_depotitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depotitem',
            name='quantity',
        ),
        migrations.CreateModel(
            name='DepotItemCashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('FEE', 'Fee')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('price_per_unit', models.DecimalField(decimal_places=6, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='stockings.depotitem')),
            ],
            options={
                'verbose_name': 'DepotItemCashflow',
                'verbose_name_plural': 'DepotItemCashflows',
                'ordering': ['-timestamp', 'item', 'flow_type'],
            },
        ),
    ]
