# Generated by Django 6.0.6 on 2026-06-19 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0006_remove_depotitem_quantity_depotitemcashflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depotitemcashflow',
            options={'ordering': ['-timestamp'], 'verbose_name': 'DepotItemCashflow', 'verbose_name_plural': 'DepotItemCashflows'},
        ),
        migrations.AddField(
            model_name='depotitemcashflow',
            name='fees',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='depotitemcashflow',
            name='taxes',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='depotitemcashflow',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='depotitemcashflow',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
