# Generated by Django 6.0.6 on 2026-06-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0007_alter_depotitemcashflow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemprice',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stockings.stockitem', unique_for_date='_timestamp'),
        ),
    ]
