# Generated by Django 6.0.6 on 2026-06-26 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0008_alter_stockitemprice_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemprice',
            name='_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
