# Generated by Django 3.0.5 on 2020-04-28 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stockings.models.stockitem


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0008_auto_20200428_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('_costs_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('_costs_currency', models.CharField(default='EUR', max_length=3)),
                ('_price_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('_price_currency', models.CharField(default='EUR', max_length=3)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockings.Portfolio')),
                ('stock_item', models.ForeignKey(on_delete=models.SET(stockings.models.stockitem.StockItem.get_sentinel_item), related_name='+', to='stockings.StockItem')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
    ]
