# Generated by Django 3.0.5 on 2020-04-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0009_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockings.StockItem'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stockings.StockItem'),
        ),
    ]
