# Generated by Django 6.0.6 on 2026-06-27 14:03

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0009_alter_stockitemprice__timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemprice',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stockings.stockitem'),
        ),
        migrations.AddConstraint(
            model_name='stockitemprice',
            constraint=models.UniqueConstraint(models.F('stock_item'), django.db.models.functions.datetime.TruncDate('_timestamp'), name='unique_stock_item_price_per_day'),
        ),
    ]
