# Generated by Django 6.0.6 on 2026-07-02 11:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0010_alter_stockitemprice_stock_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('FEE', 'Fee')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_per_unit', models.DecimalField(decimal_places=6, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fees', models.DecimalField(decimal_places=6, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('taxes', models.DecimalField(decimal_places=6, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='stockings.depotitem')),
            ],
            options={
                'verbose_name': 'Cashflow',
                'verbose_name_plural': 'Cashflows',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='DepotItemCashflow',
        ),
    ]
