# Generated by Django 6.0.6 on 2026-07-02 18:45

import stockings.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0011_cashflow_delete_depotitemcashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='currency',
            field=models.CharField(default=stockings.settings._read_default_currency, max_length=3),
        ),
    ]
