# Generated by Django 3.0.5 on 2020-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0011_auto_20200429_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='_expenses_amount',
            new_name='_cash_in_amount',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='_expenses_timestamp',
            new_name='_cash_in_timestamp',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='_proceeds_amount',
            new_name='_cash_out_amount',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='_proceeds_timestamp',
            new_name='_cash_out_timestamp',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='_deposit_amount',
            new_name='_stock_value_amount',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='_deposit_timestamp',
            new_name='_stock_value_timestamp',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_costs_currency',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_deposit_currency',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_expenses_currency',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_proceeds_currency',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
