# Generated by Django 6.0.6 on 2026-07-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0012_cashflow_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='fees',
            new_name='_fees',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='price_per_unit',
            new_name='_price_per_unit',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='taxes',
            new_name='_taxes',
        ),
    ]
