# Generated by Django 3.0.5 on 2020-05-21 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0012_auto_20200504_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='_latest_price_currency',
            new_name='_currency',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='_latest_price_amount',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='_latest_price_timestamp',
        ),
        migrations.CreateModel(
            name='StockItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_price_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('_price_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockings.StockItem', unique_for_date='_price_timestamp')),
            ],
            options={
                'verbose_name': 'Stock Item Price',
                'verbose_name_plural': 'Stock Item Prices',
            },
        ),
    ]
