# Generated by Django 3.0.5 on 2020-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0013_auto_20200521_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_currency',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='_costs_currency',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='_price_currency',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
