# Generated by Django 3.0.5 on 2020-06-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0014_auto_20200608_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_cash_in_amount',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_cash_in_timestamp',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_cash_out_amount',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_cash_out_timestamp',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_costs_amount',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_costs_timestamp',
        ),
    ]
