# Generated by Django 3.0.5 on 2020-06-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0015_auto_20200614_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_stock_count',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stock_item',
        ),
        migrations.AddField(
            model_name='trade',
            name='portfolioitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stockings.PortfolioItem'),
            preserve_default=False,
        ),
    ]
