# Generated by Django 3.0.5 on 2020-06-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0016_auto_20200622_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='stock_item',
            new_name='stockitem',
        ),
        migrations.RenameField(
            model_name='stockitemprice',
            old_name='stock_item',
            new_name='stockitem',
        ),
        migrations.AlterUniqueTogether(
            name='portfolioitem',
            unique_together={('portfolio', 'stockitem')},
        ),
    ]
