# Generated by Django 3.0.5 on 2020-06-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0017_auto_20200625_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitemprice',
            name='stockitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stockings.StockItem', unique_for_date='_price_timestamp'),
        ),
    ]
