# Generated by Django 3.0.5 on 2020-07-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0018_auto_20200630_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_stock_value_amount',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='_stock_value_timestamp',
        ),
    ]
