# Generated by Django 3.0.5 on 2020-07-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0019_auto_20200707_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['user', 'name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['portfolio', 'stockitem'], 'verbose_name': 'Portoflio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name', 'isin'], 'verbose_name': 'Stock Item', 'verbose_name_plural': 'Stock Items'},
        ),
        migrations.AlterModelOptions(
            name='stockitemprice',
            options={'get_latest_by': '_price_timestamp', 'ordering': ['-_price_timestamp', 'stockitem'], 'verbose_name': 'Stock Item Price', 'verbose_name_plural': 'Stock Item Prices'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
    ]
