# Generated by Django 3.0.8 on 2020-08-07 11:25

from django.db import migrations, models
import stockings.settings


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0020_auto_20200710_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='_currency',
            field=models.CharField(default=stockings.settings._read_default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='_currency',
            field=models.CharField(default=stockings.settings._read_default_currency, max_length=3),
        ),
    ]
