# Generated by Django 3.0.8 on 2020-08-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockings', '0021_auto_20200807_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolioitems', to='stockings.Portfolio'),
        ),
    ]
