# Generated by Django 6.0.6 on 2026-07-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YFinanceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('stock_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yfinance_mapping', to='stockings.stockitem')),
            ],
            options={
                'verbose_name': 'YFinance Mapping',
                'verbose_name_plural': 'YFinance Mappings',
            },
        ),
    ]
