# Generated by Django 6.0.6 on 2026-06-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockings', '0010_alter_stockitemprice_stock_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YFinanceMapping',
            fields=[
                ('stock_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='yfinance_mapping', serialize=False, to='stockings.stockitem')),
                ('ticker', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'YFinance Mapping',
                'verbose_name_plural': 'YFinance Mappings',
            },
        ),
    ]
